import type { Profession } from '@/types/profession'

export const PROFESSIONS: Profession[] = [
  {
    id: 'janitor',
    title: 'Janitor',
    salary: 1600,
    taxes: 280,
    mortgage: 200,
    schoolLoan: 0,
    carLoan: 60,
    creditCard: 60,
    otherExpenses: 300,
    perChildExpense: 70,
    bankLoan: 700,
    description: 'Building maintenance professional with stable income',
    difficulty: 'easy'
  },
  {
    id: 'secretary',
    title: 'Secretary',
    salary: 2500,
    taxes: 460,
    mortgage: 400,
    schoolLoan: 0,
    carLoan: 80,
    creditCard: 60,
    otherExpenses: 570,
    perChildExpense: 140,
    bankLoan: 930,
    description: 'Administrative professional with organizational expertise',
    difficulty: 'easy'
  },
  {
    id: 'truck_driver',
    title: 'Truck Driver',
    salary: 2500,
    taxes: 460,
    mortgage: 400,
    schoolLoan: 0,
    carLoan: 80,
    creditCard: 60,
    otherExpenses: 570,
    perChildExpense: 140,
    bankLoan: 930,
    description: 'Transportation professional on the open road',
    difficulty: 'easy'
  },
  {
    id: 'mechanic',
    title: 'Mechanic',
    salary: 2000,
    taxes: 360,
    mortgage: 300,
    schoolLoan: 0,
    carLoan: 60,
    creditCard: 60,
    otherExpenses: 450,
    perChildExpense: 110,
    bankLoan: 770,
    description: 'Skilled technician keeping vehicles running',
    difficulty: 'easy'
  },
  {
    id: 'police_officer',
    title: 'Police Officer',
    salary: 3000,
    taxes: 580,
    mortgage: 400,
    schoolLoan: 0,
    carLoan: 100,
    creditCard: 60,
    otherExpenses: 690,
    perChildExpense: 160,
    bankLoan: 1170,
    description: 'Law enforcement professional serving the community',
    difficulty: 'medium'
  },
  {
    id: 'nurse',
    title: 'Nurse',
    salary: 3100,
    taxes: 600,
    mortgage: 400,
    schoolLoan: 30,
    carLoan: 100,
    creditCard: 90,
    otherExpenses: 710,
    perChildExpense: 170,
    bankLoan: 1170,
    description: 'Healthcare professional caring for patients',
    difficulty: 'medium'
  },
  {
    id: 'teacher',
    title: 'Teacher (K-12)',
    salary: 3300,
    taxes: 630,
    mortgage: 500,
    schoolLoan: 60,
    carLoan: 100,
    creditCard: 90,
    otherExpenses: 760,
    perChildExpense: 180,
    bankLoan: 1160,
    description: 'Educator shaping young minds',
    difficulty: 'medium'
  },
  {
    id: 'engineer',
    title: 'Engineer',
    salary: 4900,
    taxes: 1050,
    mortgage: 700,
    schoolLoan: 60,
    carLoan: 140,
    creditCard: 120,
    otherExpenses: 1090,
    perChildExpense: 250,
    bankLoan: 1740,
    description: 'Technical professional solving complex problems',
    difficulty: 'medium'
  },
  {
    id: 'business_manager',
    title: 'Business Manager',
    salary: 4600,
    taxes: 910,
    mortgage: 700,
    schoolLoan: 60,
    carLoan: 120,
    creditCard: 90,
    otherExpenses: 1000,
    perChildExpense: 240,
    bankLoan: 1720,
    description: 'Corporate professional managing teams',
    difficulty: 'medium'
  },
  {
    id: 'airline_pilot',
    title: 'Airline Pilot',
    salary: 9500,
    taxes: 2350,
    mortgage: 1330,
    schoolLoan: 0,
    carLoan: 300,
    creditCard: 660,
    otherExpenses: 2210,
    perChildExpense: 480,
    bankLoan: 2650,
    description: 'Aviation professional flying the skies',
    difficulty: 'hard'
  },
  {
    id: 'lawyer',
    title: 'Lawyer',
    salary: 7500,
    taxes: 1830,
    mortgage: 1100,
    schoolLoan: 390,
    carLoan: 220,
    creditCard: 180,
    otherExpenses: 1650,
    perChildExpense: 380,
    bankLoan: 2130,
    description: 'Legal professional advocating for clients',
    difficulty: 'hard'
  },
  {
    id: 'doctor',
    title: 'Doctor',
    salary: 13200,
    taxes: 3420,
    mortgage: 1900,
    schoolLoan: 750,
    carLoan: 380,
    creditCard: 270,
    otherExpenses: 2880,
    perChildExpense: 640,
    bankLoan: 3600,
    description: 'Medical professional healing patients',
    difficulty: 'hard'
  }
]